before_install:
  sudo apt-get install xclip
language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - pypy
allow_failures:
  - python: pypy
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  coverage run --source=pysswords tests/test.py
after_success:
  coveralls