before_install:
  - sudo apt-get update --fix-missing
  - sudo apt-get install xclip gnupg2
language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - pypy
allow_failures:
  - python: pypy
install:
  - make develop
script:
  - make coverage
after_success:
  - pip install codecov
  - codecov
