before_install:
  sudo apt-get install xclip gpg
language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - pypy
allow_failures:
  - python: pypy
install:
- pip install -r requirements_tests.txt
- pip install .
script:
- python setup.py coverage
after_success:
- pip install codecov
- codecov
