os:
  - linux
  - osx
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install xclip; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sudo easy_install pip; fi
language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - pypy
allow_failures:
  - python: pypy
install:
  - pip install -r requirements.txt
  - pip install pytest mock coveralls
script:
  coverage run --source=py.test
after_success:
  coveralls