before_install:
  - sudo apt-get update --fix-missing
install:
  -  pip install -r requirements.txt
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
allow_failures:
    - python: "pypy"
    - python: "3.2"
    - python: "3.3"
    - python: "3.4"
script:
  - python tests/test.py